import type { PaymentRequirements } from "../types";

/**
 * Escapes a string for safe injection into JavaScript string literals
 */
function escapeString(str: string): string {
  return str
    .replace(/\\/g, "\\\\")
    .replace(/"/g, '\\"')
    .replace(/'/g, "\\'")
    .replace(/\n/g, "\\n")
    .replace(/\r/g, "\\r")
    .replace(/\t/g, "\\t");
}

/**
 * Gets the EVM chain config
 */
function getChainConfig() {
  return {
    "base": {
      usdcAddress: "0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913",
      usdcName: "USDC",
    },
    "base-sepolia": {
      usdcAddress: "0x036CbD53842c5426634e7929541eC2318f3dCF7e",
      usdcName: "USDC",
    },
  };
}

interface EvmPaywallOptions {
  amount: number;
  paymentRequirements: PaymentRequirements[];
  currentUrl: string;
  testnet: boolean;
  cdpClientKey?: string;
  appName?: string;
  appLogo?: string;
  sessionTokenEndpoint?: string;
}

/**
 * Generates EVM-specific paywall HTML
 */
export function getEvmPaywallHtml(options: EvmPaywallOptions): string {
  let EVM_PAYWALL_TEMPLATE: string;
  
  try {
    // Will be generated by build script
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    const template = require("./gen/template");
    EVM_PAYWALL_TEMPLATE = template.EVM_PAYWALL_TEMPLATE;
  } catch {
    // Template not built yet, return placeholder
    return `<!DOCTYPE html><html><body><h1>EVM Paywall (run pnpm build:paywall to generate full template)</h1></body></html>`;
  }

  const { amount, testnet, paymentRequirements, currentUrl, cdpClientKey, appName, appLogo, sessionTokenEndpoint } = options;

  const logOnTestnet = testnet
    ? "console.log('EVM Payment requirements initialized:', window.x402);"
    : "";

  const config = getChainConfig();

  const configScript = `
  <script>
    window.x402 = {
      amount: ${amount},
      paymentRequirements: ${JSON.stringify(paymentRequirements)},
      testnet: ${testnet},
      currentUrl: "${escapeString(currentUrl)}",
      config: {
        chainConfig: ${JSON.stringify(config)},
      },
      cdpClientKey: "${escapeString(cdpClientKey || "")}",
      appName: "${escapeString(appName || "")}",
      appLogo: "${escapeString(appLogo || "")}",
      sessionTokenEndpoint: "${escapeString(sessionTokenEndpoint || "")}",
    };
    ${logOnTestnet}
  </script>`;

  return EVM_PAYWALL_TEMPLATE.replace("</head>", `${configScript}\n</head>`);
}

